### ISSUE TITLE
Default platform value on mac

### ISSUE THREAD

**Issue by JulesFaucherre** [folder/xdg#3]
In the doc it is stated that the default value for `options.platform` is `process.platform` but it doesn't seem like it on mac
I'm on a mid-2014 MacBook Pro with BigSur

Expected behaviour:
```
> xdg()
{
  cache: '/Users/nicolasfaucherre/Library/Caches',
  config: '/Users/nicolasfaucherre/Library/Application Support',
  ...
```

Current behaviour:
```
> xdg()
{
  cache: '/Users/nicolasfaucherre/.cache',
  config: '/Users/nicolasfaucherre/.config',
  ...
```

After seeing the code, I would gladly open a pr for that by it feels like it is designed like this on purpose. In the case it is on purpose, it would be great to know why and maybe better to say it in the doc

**Comment by jonschlinkert** [comment]
Closing, since I believe this was resolved by https://github.com/folder/xdg/pull/4.  I'll be publishing a major release since, although this is definitely a bug fix, it will break people's code if I do a patch or minor. Thanks for bringing this to my attention. If anyone still has issues with this, please create a new issue after the release.
